language: java
jdk:
- openjdk11
addons:
  sonarcloud:
    organization: kseniia-makarova
    token: oLwPrw4YX6wSV4wimzZvdabkkTGFvCBm0W0Y2Izth4w3Z3R+2ijvqyV7930f8EfWVFKEQAj/m+eutv1cGKBNztrRc0iPRg2B8cUicEmt1/Dx6LRiijpvUm1r9HTGtkC7Nio3UxBf2yfNQerONa4mLbk+CxmYlSF82zXEMBab/iNliWpyW7c2eQ3zGtROIJ4WFqTHxbVzQL1Pan9EXX74kdJdQWYyIL4Au7+1bruxmef6jShjtfTxghUpl0rX3qYcyoOKX3648fip7FvzZfNfZ0el8zkyhhmlb1fNmdempKUyOueymrlQetoBZZCG03Hx2I8eySmYhPv8G03P1LU69/TP4xeDfT4s8en8SMl09AJpATf8PLV4+PHhFJuOdi11EOycGe1NjJpEeJerB78SQGBqr4pEqrl4OGFBwOAbhUyJbkRNX+YezycgxZik7e0aVzo83uNtaag7YLQIQCQeVA2+S5JQA0Vti0ydUmn7aoJDT+g+RJcDviJdRDSZRDs51CkdjXZXwuWvwFKB8XWfza2ARGHfqWWSedA11h4YIT+2mf7/rGLxmW8LuIT65THmPDpfaEb8vOf1uU6b/BcAQambbuCja9MgZmBGsfh2roeCcThIKuiHw3opfrCfWy/CRARuYTMxnduJUSpilKKu394GkGRkvs9SWMD9BvlO0KI=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=KseniiaMakarova_internet-shop
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
    secure: YqhMQmj5VEMOJdggjMfSXpy039IhYf39cu7oV33fNRFH4M7NTO5bBpDd34wTWMvt34bqFt7gIrlNFo3bCkjUU3ibj+PtlcmRtfDwBG7IFWG9yc+K1+pj+XCq8pByXE2es5+Cwhhp+t5rz4/L6fFIvNUxJKQ94yRv/WS7FoOIvW0LWZMMQiv/BwXd5fD54hV9UwpzK5rQoso2F+SJOsr37nhmumNW2ni3AQK1qBMyxzBeb6liZpoE4njQ1E4zpHXsJEsaR9hmlU+KjmDeZuvwwNSfYfj9CI/6MOu+stA7nSf8EkjC/p09vNZpv1fEXqauVw4nJHGbf0i7oCMokkAuFA1L8UnK1/1/BUYgAEfyKrd4XXnD/o1KZB2uai6AWNFWZAiBvkm8Vao0p8C+ZosepxL3tFARv/vLG6Z0q5j1ae0Tgzpxxs1hwZvVP1NiJK70mcgltOs20tJamxpkXRKa+qzbbgYqRxPel+46d8/otclzue2yEVXh2HS+Ne9DS39zZwq03CSDpaEhu+eDwMvQfNZkN80byoPEpsh/iwg+CukKqYyTji2zlqibhiBZ7CRd6O13LEXcnlbPBX6qcYc1/3+AF8U8lbfMNLHpc1JlhtfGPIMGWyhq5TaJjCPUMRvrtGBd2HONBiJLifn8VSsXCGgFs1OxKpLY0umLzg+/lVg=
