language: java
jdk:
  - openjdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=KseniiaMakarova_internet-shop

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "kseniia-makarova"
    token:
      secure: "gP4H99hsW2mg67Vh06uLMp8oxr6u/5ZX6lhaOkEaPzyUFaRo2fZ322wkjR+dlyLzoKspcIrLmo/2smxG0mRneJgg3sI61dU+PW0B6V8b2G5wgqoV26B7Q+o8wye3bWRZAR6ZhSH8Eke+w
    Gj5D4X/r2xFm8jdpiVOv/v65B3MiX+N3mqO+E7fBW97GoOEvqKdS4Cnp0vomkSZSmFlheAsFkDf/tjoyaZbdyki7u3mrxYL9egIZSSuQ2XaJAJyurdAuY8AJoNv+BjXXiTROiN3BZfhCMh1PKwzsWMTO
    dSOc8/oY+OoHRxaEfQSeVBTXdkZL33KXSpGFbjs4PXmeFr0PkrP3evkK9a2Rs8MzQSlysHATdh9ujsST3cDj6Hy1crDMBSe2EoxG9SghEvHaU9ImJfavfRt/4PBJdW3GljovQERmaeipFHpokcR0JyaC
    LBen9mGkaroAG/uYDliDY4mvgQ1pWdxUMmtN84iR1I8XB63VXd/5+gFC4G1wFvOvkmogN/7R+bijS+X2xm1VYULXpRF2VQQYpHTbivSZYaHiC1iANiuYC/iWpqyKX6dKEI1ljdJT+lG5nU0JOhJVO7HI
    R0q8oysTw/0+yyPS6hQjC5FlA8cm5h9rnOIuuRxIb5u7znhpWRzTqhKt1Z1R4eT+F00i2e/s/mcw4/gALmNpVU="
