language: java
jdk:
  - openjdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=KseniiaMakarova_internet-shop

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "kseniia-makarova"
    token:
      secure: "XcQiVaj6RdW6PL9DE6s0V0cDYVYGTHn6kNhn8SLE+kwiN+FpWtND2M+2zXPZ1/DJK99rVwsTHhWbIIDkFgih3mhEm9VTJQNcQS9SO8hCO4w5Ii+wu5JyPzetRd8P/hB5/twPY9Z7LMCf4
      4jlgH762Pbr0T9G2Q+BWtmeyTnpUU2vpkB5sOY4nWzILLPP0jf5VQVk6780vHgompCNKFwRkIPyCL/QoLyvKZC6smW+QUxvVw/XvbbIBM7qUN2SUUS2CWB1FQYwU88ECVkRBtJfNaEAOFX9GcV+89sim
      PdsU8C5hlS84i8hNNW7jYul5D05rYGGKJU+6GMoAe2SkGACpZYb+F//xfcUAm4fz0hWASp0O7OYrJynQlr0KVjvyIZcvAA4B99ZuDOZLc6zTvwocI4K4BhGdW4DP6gLgi/OUZT/KRrocQ/NvhKWDQW9x
      yoA/86s7GLL6UV32HUm7UZ5VHlgUWxdPpldx5BrPWyiN3mCOhKD32Kgp4E2jGWT6IW2KwEYBjxetSb07dPNN09B1Eu2XHpf6gb8beccpJp5n5VHRga3EydqonFFrTRVPBmF7ZbpWN1se96A2Xw+oC7rH
      xF8PgtBipEPukztEjTTH6k9CyPdUdnpyRmswywwxXnG/PzXM8Kihqz132P3r6EczB9CsnbBQMEviGTPHqJ4Oz0="
