language: java
jdk:
  - openjdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=KseniiaMakarova_internet-shop

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "kseniia-makarova"
    token:
      secure: "nG+Qomgf4dSeKdIbvMsE1R/CfsQTKe5bPrZXN6jX5IJXNm+2y+0tmadUB0w0eXcLlhb/yjIhdKelSwDJ1L6m6aCRXEfHO3tl5jKdb1eKxF6M5EE8b7bPJ++eIvO3iD1SQn5lknlvCAbEh
        LCpvbwHWKVbQrn+yablQ5VA6VONbvFOjBfAKMBikbWocYe9lsq0p2aI7FY8+MHYKStSu/C8I+BWX4smOoreZBRpYRYNYxqkgr5PMDYVwGApIvxvO/exNcupfIZlUjiC3Zz50q7+pLozaH/EKB5D3i68/
        UzwU/nc2tlXUD5gveigtUEXWyU3caJJPp7ep/WxIY902SYle6qMX/EaHhNPoFngjGDTkvmia/qoWPV94Rs4yZmfAdcReqhLgPUyJc8yjMTeE2GZKARsIzBPzlIheV746VRrxN4AfmJDnqxvY1jRGdqES
        CgqkFEdD9mgbGRsDjzzbcaTR+RjBchuG/Z2xrGlrgJQHXGr1LDPu30T0lO6ilQoCMvIuOrS9wiEl6UhmD3qXdqNAHrf/T9UQsP1GfPrnC/uN2pmj2zxlsfXTYj1nZE4p0EUmAePkdkxfOU+PFHZmwyKp
        Nr9juOzUkqX9EDEZulg2yWI4pw/Db5qVt2Ccg28mF45lYyie+zLDy3OfBo64mVKujFiVPc0jflFQWXjBlXlOEY="

