language: java

jdk:
  - openjdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=KseniiaMakarova_internet-shop -Dsonar.organization=kseniia-makarova -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=60a899a3971c5114efd5738080c9b09cb54140b9

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "kseniia-makarova"
    token:
      secure: "R6WpI8M9kwAvgklA8LocG4Fg3O4CwFfCljpN9wsil6WD6IKCuEITGgbg6pagvhfuPIIJd4lQt1bXEYLXT2CvW3zPShL4YKchHxGr1mEdKyyqyDkopZseiKag7QgiEc37gytJkyxPoRLd/
      k6zpOIaTE4FTo0wpYKxusUlAQoaDBt5cLitSP+GIWQ10Qsk2jKGR+ialacVUU73aTqC/S/vl+pWRK1MAhrWL+3ojuErhtCXU5y8/ys6qm7/YLIHousv/7K4JjU2lmHpcvGWAtX+ZPkvwEm3uZhffVCt6
      g4BarOPu5qU4D0JlsKxVkYdBJpF7RGF8/18BRFK2jX51jinJZuxQ3ZS1SyhxaB4xzgHOekqdr35udPEesicH4yqZbAwFDB6ULAnY87G7UkppwbEDNVASa+kugyaI5V4iYn1aHrP0IGe6K99D+tKl8uhy
      SoviMEOgi/gfniQxRRONoJsBKqPVhOYNULVPZkGiPR75zfGKAGaue6zrL3RnH+Ja/E9HMkCkFAgOLxly7xcnc/6aQlQ9TsJdPu+Foi5P0kO/X8FgYY7LO6GgdjPrm+WPhVybXT5COAOvdfaL/EJnLUd2
      CLU4j5xDK5hY6CmhUhxo0UJWFvn2SS4zNxVkAtCqQnvEEHVdV9zK2TbXo9YiJ9pJUKDF6+LXLoi35qeTsXo+6U="
