language: java
jdk:
  - openjdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=KseniiaMakarova_internet-shop

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "kseniia-makarova"
    token:
      secure: "9qVWpLH74DkG4UVsZr0hwOt5yAI3+31aUvLU728wHNuOZ17wSpTRvGBUxTzjmQjyTW5COOzsYd6btE5vG5j92ScdH5hu//2mlKxIb2g8UZpucYhlN3L469efVS1+8YcxWxQxOFzAUTTzC
    sns2x3dVzZp2LnLDlodYwovYtV+ksajVJXmsCEWox/c6nIcr4SpoA3eA2WbGlMA2MBIez2+NLCGiA3WqqWhCcAw0EnWInHE+f8HvBpFdCTOI1NsGlAWcK0vjQunFTSI7R3ejFFq1sdb3UepafeKfbB2e
    QaqFVHhV00PIdpYiP3w+jxptey4CPSSUHjkvASGDQYnnBa8CBZ3nuD79TVjthzTBL4XOh5XShwnEYpEVWaqn8RnABcisEcuMiZtG+j/6eORdvrfOI57Sbd8rXgXmYnyt77sEumVwNrPS+8jidVUuXbca
    fGcs1j2aeZlh2vk7jHko1bSqj+lEuDYjxGanOF9aPWc6x84y7t0wF8XfUE9e4fb6A5EfEKh5x1vMDmVQaFKnaEjfAzWVhP7HD1sXbmI1+7otzxFL8HsvQbVgUtanz8tUJ889xH3gOUl1+Xq2wmqnspB3
    dRo0zBuTZjeQ7soiAw7VJp3uX6Jtd+AaaykxDZtwo544mV3v7Vcs7qPzuzwlUPtEM9bSoBsTaNPcPQTjr0objM="
